# Generated by Django 4.2 on 2023-12-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('image', models.ImageField(null=True, upload_to='announcement_image/')),
                ('created', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_announ', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calary', models.DecimalField(decimal_places=0, max_digits=6)),
                ('type_of_work', models.CharField(choices=[('LOCAL', 'local'), ('REMOTE', 'remote')], max_length=10)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='bulletin_board.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other', to='bulletin_board.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField()),
                ('area', models.FloatField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house', to='bulletin_board.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('MERS', 'MERSEDES'), ('AUDI', 'AUDI')], max_length=10)),
                ('year', models.IntegerField()),
                ('engine_power', models.FloatField()),
                ('color', models.CharField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('USE', 'IN_USE')], max_length=10)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='bulletin_board.announcement')),
            ],
        ),
    ]
