# Generated by Django 4.2 on 2023-12-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('house', 'house'), ('car', 'car'), ('other', 'other')], max_length=10, null=True),
        ),
    ]
